update=10/2/2018 4:49:21 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=switches
LibName4=relays
LibName5=motors
LibName6=transistors
LibName7=conn
LibName8=linear
LibName9=regul
LibName10=74xx
LibName11=cmos4000
LibName12=adc-dac
LibName13=memory
LibName14=xilinx
LibName15=microcontrollers
LibName16=dsp
LibName17=microchip
LibName18=analog_switches
LibName19=motorola
LibName20=texas
LibName21=intel
LibName22=audio
LibName23=interface
LibName24=digital-audio
LibName25=philips
LibName26=display
LibName27=cypress
LibName28=siliconi
LibName29=opto
LibName30=atmel
LibName31=contrib
LibName32=valves
LibName33=E:/softwares/KI CAD/KiCad/share/kicad/library/4xxx
LibName34=E:/softwares/KI CAD/KiCad/share/kicad/library/4xxx_IEEE
LibName35=E:/softwares/KI CAD/KiCad/share/kicad/library/74xgxx
LibName36=E:/softwares/KI CAD/KiCad/share/kicad/library/74xx
LibName37=E:/softwares/KI CAD/KiCad/share/kicad/library/74xx_IEEE
LibName38=E:/softwares/KI CAD/KiCad/share/kicad/library/ac-dc
LibName39=E:/softwares/KI CAD/KiCad/share/kicad/library/actel
LibName40=E:/softwares/KI CAD/KiCad/share/kicad/library/adc-dac
LibName41=E:/softwares/KI CAD/KiCad/share/kicad/library/allegro
LibName42=E:/softwares/KI CAD/KiCad/share/kicad/library/Altera
LibName43=E:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Audio
LibName44=E:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Buffer
LibName45=E:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Current
LibName46=E:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Difference
LibName47=E:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Instrumentation
LibName48=E:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Operational
LibName49=E:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Video
LibName50=E:/softwares/KI CAD/KiCad/share/kicad/library/Analog
LibName51=E:/softwares/KI CAD/KiCad/share/kicad/library/Analog_ADC
LibName52=E:/softwares/KI CAD/KiCad/share/kicad/library/Analog_DAC
LibName53=E:/softwares/KI CAD/KiCad/share/kicad/library/analog_devices
LibName54=E:/softwares/KI CAD/KiCad/share/kicad/library/Analog_Switch
LibName55=E:/softwares/KI CAD/KiCad/share/kicad/library/analog_switches
LibName56=E:/softwares/KI CAD/KiCad/share/kicad/library/arduino
LibName57=E:/softwares/KI CAD/KiCad/share/kicad/library/atmel
LibName58=E:/softwares/KI CAD/KiCad/share/kicad/library/audio
LibName59=E:/softwares/KI CAD/KiCad/share/kicad/library/battery_management
LibName60=E:/softwares/KI CAD/KiCad/share/kicad/library/bbd
LibName61=E:/softwares/KI CAD/KiCad/share/kicad/library/bosch
LibName62=E:/softwares/KI CAD/KiCad/share/kicad/library/brooktre
LibName63=E:/softwares/KI CAD/KiCad/share/kicad/library/cmos_ieee
LibName64=E:/softwares/KI CAD/KiCad/share/kicad/library/cmos4000
LibName65=E:/softwares/KI CAD/KiCad/share/kicad/library/Comparator
LibName66=E:/softwares/KI CAD/KiCad/share/kicad/library/conn
LibName67=E:/softwares/KI CAD/KiCad/share/kicad/library/Connector
LibName68=E:/softwares/KI CAD/KiCad/share/kicad/library/Connector_Generic
LibName69=E:/softwares/KI CAD/KiCad/share/kicad/library/Connector_Generic_MountingPin
LibName70=E:/softwares/KI CAD/KiCad/share/kicad/library/Connector_Generic_Shielded
LibName71=E:/softwares/KI CAD/KiCad/share/kicad/library/contrib
LibName72=E:/softwares/KI CAD/KiCad/share/kicad/library/Converter_ACDC
LibName73=E:/softwares/KI CAD/KiCad/share/kicad/library/Converter_DCDC
LibName74=E:/softwares/KI CAD/KiCad/share/kicad/library/CPLD_Altera
LibName75=E:/softwares/KI CAD/KiCad/share/kicad/library/CPLD_Xilinx
LibName76=E:/softwares/KI CAD/KiCad/share/kicad/library/CPU
LibName77=E:/softwares/KI CAD/KiCad/share/kicad/library/CPU_NXP_6800
LibName78=E:/softwares/KI CAD/KiCad/share/kicad/library/CPU_NXP_68000
LibName79=E:/softwares/KI CAD/KiCad/share/kicad/library/CPU_PowerPC
LibName80=E:/softwares/KI CAD/KiCad/share/kicad/library/cypress
LibName81=E:/softwares/KI CAD/KiCad/share/kicad/library/dc-dc
LibName82=E:/softwares/KI CAD/KiCad/share/kicad/library/device
LibName83=E:/softwares/KI CAD/KiCad/share/kicad/library/digital-audio
LibName84=E:/softwares/KI CAD/KiCad/share/kicad/library/diode
LibName85=E:/softwares/KI CAD/KiCad/share/kicad/library/Diode_Bridge
LibName86=E:/softwares/KI CAD/KiCad/share/kicad/library/Diode_Laser
LibName87=E:/softwares/KI CAD/KiCad/share/kicad/library/display
LibName88=E:/softwares/KI CAD/KiCad/share/kicad/library/Display_Character
LibName89=E:/softwares/KI CAD/KiCad/share/kicad/library/Display_Graphic
LibName90=E:/softwares/KI CAD/KiCad/share/kicad/library/Driver_Display
LibName91=E:/softwares/KI CAD/KiCad/share/kicad/library/Driver_FET
LibName92=E:/softwares/KI CAD/KiCad/share/kicad/library/Driver_LED
LibName93=E:/softwares/KI CAD/KiCad/share/kicad/library/Driver_Motor
LibName94=E:/softwares/KI CAD/KiCad/share/kicad/library/Driver_Relay
LibName95=E:/softwares/KI CAD/KiCad/share/kicad/library/dsp
LibName96=E:/softwares/KI CAD/KiCad/share/kicad/library/DSP_AnalogDevices
LibName97=E:/softwares/KI CAD/KiCad/share/kicad/library/DSP_Freescale
LibName98=E:/softwares/KI CAD/KiCad/share/kicad/library/DSP_Microchip_DSPIC33
LibName99=E:/softwares/KI CAD/KiCad/share/kicad/library/DSP_Motorola
LibName100=E:/softwares/KI CAD/KiCad/share/kicad/library/DSP_Texas
LibName101=E:/softwares/KI CAD/KiCad/share/kicad/library/elec-unifil
LibName102=E:/softwares/KI CAD/KiCad/share/kicad/library/ESD_Protection
LibName103=E:/softwares/KI CAD/KiCad/share/kicad/library/Filter
LibName104=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Lattice
LibName105=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Microsemi
LibName106=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx
LibName107=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Artix7
LibName108=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Kintex7
LibName109=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Spartan6
LibName110=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Virtex5
LibName111=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Virtex6
LibName112=E:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Virtex7
LibName113=E:/softwares/KI CAD/KiCad/share/kicad/library/ftdi
LibName114=E:/softwares/KI CAD/KiCad/share/kicad/library/gennum
LibName115=E:/softwares/KI CAD/KiCad/share/kicad/library/GPU
LibName116=E:/softwares/KI CAD/KiCad/share/kicad/library/Graphic
LibName117=E:/softwares/KI CAD/KiCad/share/kicad/library/graphic_symbols
LibName118=E:/softwares/KI CAD/KiCad/share/kicad/library/hc11
LibName119=E:/softwares/KI CAD/KiCad/share/kicad/library/infineon
LibName120=E:/softwares/KI CAD/KiCad/share/kicad/library/intel
LibName121=E:/softwares/KI CAD/KiCad/share/kicad/library/interface
LibName122=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_CAN_LIN
LibName123=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_CurrentLoop
LibName124=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_Ethernet
LibName125=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_Expansion
LibName126=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_HID
LibName127=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_LineDriver
LibName128=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_Optical
LibName129=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_Telecom
LibName130=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_UART
LibName131=E:/softwares/KI CAD/KiCad/share/kicad/library/Interface_USB
LibName132=E:/softwares/KI CAD/KiCad/share/kicad/library/intersil
LibName133=E:/softwares/KI CAD/KiCad/share/kicad/library/ir
LibName134=E:/softwares/KI CAD/KiCad/share/kicad/library/Isolator
LibName135=E:/softwares/KI CAD/KiCad/share/kicad/library/Isolator_Analog
LibName136=E:/softwares/KI CAD/KiCad/share/kicad/library/Jumper
LibName137=E:/softwares/KI CAD/KiCad/share/kicad/library/Lattice
LibName138=E:/softwares/KI CAD/KiCad/share/kicad/library/LED
LibName139=E:/softwares/KI CAD/KiCad/share/kicad/library/leds
LibName140=E:/softwares/KI CAD/KiCad/share/kicad/library/LEM
LibName141=E:/softwares/KI CAD/KiCad/share/kicad/library/linear
LibName142=E:/softwares/KI CAD/KiCad/share/kicad/library/Logic_LevelTranslator
LibName143=E:/softwares/KI CAD/KiCad/share/kicad/library/logic_programmable
LibName144=E:/softwares/KI CAD/KiCad/share/kicad/library/maxim
LibName145=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_AnalogDevices
LibName146=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Cypress
LibName147=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Espressif
LibName148=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Intel
LibName149=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_8051
LibName150=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_ATmega
LibName151=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_ATtiny
LibName152=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_AVR
LibName153=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC10
LibName154=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC12
LibName155=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC16
LibName156=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC18
LibName157=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC24
LibName158=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC32
LibName159=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_SAME
LibName160=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_SAML
LibName161=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Module
LibName162=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Nordic
LibName163=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_ColdFire
LibName164=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_HC11
LibName165=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_HC12
LibName166=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_HCS12
LibName167=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_Kinetis
LibName168=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_LPC
LibName169=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_MAC7100
LibName170=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_MCore
LibName171=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_S08
LibName172=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Parallax
LibName173=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_SiFive
LibName174=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_SiliconLabs
LibName175=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM8
LibName176=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F0
LibName177=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F1
LibName178=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F2
LibName179=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F3
LibName180=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F4
LibName181=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F7
LibName182=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32H7
LibName183=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32L0
LibName184=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32L1
LibName185=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32L4
LibName186=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32L4+
LibName187=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Texas
LibName188=E:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Texas_MSP430
LibName189=E:/softwares/KI CAD/KiCad/share/kicad/library/mechanical
LibName190=E:/softwares/KI CAD/KiCad/share/kicad/library/memory
LibName191=E:/softwares/KI CAD/KiCad/share/kicad/library/Memory_Controller
LibName192=E:/softwares/KI CAD/KiCad/share/kicad/library/Memory_EEPROM
LibName193=E:/softwares/KI CAD/KiCad/share/kicad/library/Memory_EPROM
LibName194=E:/softwares/KI CAD/KiCad/share/kicad/library/Memory_Flash
LibName195=E:/softwares/KI CAD/KiCad/share/kicad/library/Memory_NVRAM
LibName196=E:/softwares/KI CAD/KiCad/share/kicad/library/Memory_RAM
LibName197=E:/softwares/KI CAD/KiCad/share/kicad/library/Memory_ROM
LibName198=E:/softwares/KI CAD/KiCad/share/kicad/library/Memory_UniqueID
LibName199=E:/softwares/KI CAD/KiCad/share/kicad/library/microchip
LibName200=E:/softwares/KI CAD/KiCad/share/kicad/library/microchip_dspic33dsc
LibName201=E:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic10mcu
LibName202=E:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic12mcu
LibName203=E:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic16mcu
LibName204=E:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic18mcu
LibName205=E:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic24mcu
LibName206=E:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic32mcu
LibName207=E:/softwares/KI CAD/KiCad/share/kicad/library/microcontrollers
LibName208=E:/softwares/KI CAD/KiCad/share/kicad/library/modules
LibName209=E:/softwares/KI CAD/KiCad/share/kicad/library/Motor
LibName210=E:/softwares/KI CAD/KiCad/share/kicad/library/motor_drivers
LibName211=E:/softwares/KI CAD/KiCad/share/kicad/library/motorola
LibName212=E:/softwares/KI CAD/KiCad/share/kicad/library/motors
LibName213=E:/softwares/KI CAD/KiCad/share/kicad/library/msp430
LibName214=E:/softwares/KI CAD/KiCad/share/kicad/library/nordicsemi
LibName215=E:/softwares/KI CAD/KiCad/share/kicad/library/nxp
LibName216=E:/softwares/KI CAD/KiCad/share/kicad/library/nxp_armmcu
LibName217=E:/softwares/KI CAD/KiCad/share/kicad/library/onsemi
LibName218=E:/softwares/KI CAD/KiCad/share/kicad/library/opto
LibName219=E:/softwares/KI CAD/KiCad/share/kicad/library/Oscillator
LibName220=E:/softwares/KI CAD/KiCad/share/kicad/library/Oscillators
LibName221=E:/softwares/KI CAD/KiCad/share/kicad/library/philips
LibName222=E:/softwares/KI CAD/KiCad/share/kicad/library/PIC18F4525-I_P
LibName223=E:/softwares/KI CAD/KiCad/share/kicad/library/Potentiometer_Digital
LibName224=E:/softwares/KI CAD/KiCad/share/kicad/library/power
LibName225=E:/softwares/KI CAD/KiCad/share/kicad/library/Power_Management
LibName226=E:/softwares/KI CAD/KiCad/share/kicad/library/Power_Protection
LibName227=E:/softwares/KI CAD/KiCad/share/kicad/library/Power_Supervisor
LibName228=E:/softwares/KI CAD/KiCad/share/kicad/library/powerint
LibName229=E:/softwares/KI CAD/KiCad/share/kicad/library/pspice
LibName230=E:/softwares/KI CAD/KiCad/share/kicad/library/Reference_Current
LibName231=E:/softwares/KI CAD/KiCad/share/kicad/library/Reference_Voltage
LibName232=E:/softwares/KI CAD/KiCad/share/kicad/library/references
LibName233=E:/softwares/KI CAD/KiCad/share/kicad/library/regul
LibName234=E:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_Controller
LibName235=E:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_Current
LibName236=E:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_Linear
LibName237=E:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_SwitchedCapacitor
LibName238=E:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_Switching
LibName239=E:/softwares/KI CAD/KiCad/share/kicad/library/Relay
LibName240=E:/softwares/KI CAD/KiCad/share/kicad/library/Relay_SolidState
LibName241=E:/softwares/KI CAD/KiCad/share/kicad/library/relays
LibName242=E:/softwares/KI CAD/KiCad/share/kicad/library/RF
LibName243=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_AM_FM
LibName244=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_Amplifier
LibName245=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_Bluetooth
LibName246=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_GPS
LibName247=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_Mixer
LibName248=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_Module
LibName249=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_RFID
LibName250=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_Switch
LibName251=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_WiFi
LibName252=E:/softwares/KI CAD/KiCad/share/kicad/library/RF_ZigBee
LibName253=E:/softwares/KI CAD/KiCad/share/kicad/library/rfcom
LibName254=E:/softwares/KI CAD/KiCad/share/kicad/library/RFSolutions
LibName255=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor
LibName256=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Audio
LibName257=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Current
LibName258=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Gas
LibName259=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Humidity
LibName260=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Magnetic
LibName261=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Motion
LibName262=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Optical
LibName263=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Pressure
LibName264=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Proximity
LibName265=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Temperature
LibName266=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Touch
LibName267=E:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Voltage
LibName268=E:/softwares/KI CAD/KiCad/share/kicad/library/sensors
LibName269=E:/softwares/KI CAD/KiCad/share/kicad/library/silabs
LibName270=E:/softwares/KI CAD/KiCad/share/kicad/library/siliconi
LibName271=E:/softwares/KI CAD/KiCad/share/kicad/library/stm8
LibName272=E:/softwares/KI CAD/KiCad/share/kicad/library/stm32
LibName273=E:/softwares/KI CAD/KiCad/share/kicad/library/supertex
LibName274=E:/softwares/KI CAD/KiCad/share/kicad/library/Switch
LibName275=E:/softwares/KI CAD/KiCad/share/kicad/library/switches
LibName276=E:/softwares/KI CAD/KiCad/share/kicad/library/texas
LibName277=E:/softwares/KI CAD/KiCad/share/kicad/library/Timer
LibName278=E:/softwares/KI CAD/KiCad/share/kicad/library/Timer_PLL
LibName279=E:/softwares/KI CAD/KiCad/share/kicad/library/Timer_RTC
LibName280=E:/softwares/KI CAD/KiCad/share/kicad/library/transf
LibName281=E:/softwares/KI CAD/KiCad/share/kicad/library/Transformer
LibName282=E:/softwares/KI CAD/KiCad/share/kicad/library/Transistor_Array
LibName283=E:/softwares/KI CAD/KiCad/share/kicad/library/Transistor_BJT
LibName284=E:/softwares/KI CAD/KiCad/share/kicad/library/Transistor_FET
LibName285=E:/softwares/KI CAD/KiCad/share/kicad/library/Transistor_IGBT
LibName286=E:/softwares/KI CAD/KiCad/share/kicad/library/transistors
LibName287=E:/softwares/KI CAD/KiCad/share/kicad/library/triac_thyristor
LibName288=E:/softwares/KI CAD/KiCad/share/kicad/library/ttl_ieee
LibName289=E:/softwares/KI CAD/KiCad/share/kicad/library/Valve
LibName290=E:/softwares/KI CAD/KiCad/share/kicad/library/valves
LibName291=E:/softwares/KI CAD/KiCad/share/kicad/library/video
LibName292=E:/softwares/KI CAD/KiCad/share/kicad/library/wiznet
LibName293=E:/softwares/KI CAD/KiCad/share/kicad/library/Worldsemi
LibName294=E:/softwares/KI CAD/KiCad/share/kicad/library/Xicor
LibName295=E:/softwares/KI CAD/KiCad/share/kicad/library/xilinx
LibName296=E:/softwares/KI CAD/KiCad/share/kicad/library/zetex
LibName297=E:/softwares/KI CAD/KiCad/share/kicad/library/Zilog
